### ISSUE TITLE
[Feat] Add Github Issue Templates

### ISSUE THREAD

**Issue by Bashamega** [open-transport-mallorca/ViaMallorca#1]
We need to implement GitHub issue templates to streamline the process of reporting issues, feature requests, and other contributions. This will improve communication and ensure that all necessary information is provided upfront. The following templates are proposed:

### 1. **Bug Report Template**
- **Title**: Bug: [Short description]
- **Description**: Describe the issue in detail.
- **Steps to Reproduce**: List steps to reproduce the bug.
- **Expected Behavior**: What should happen?
- **Actual Behavior**: What actually happened?
- **Environment**:
  - OS: 
  - Version:

### 2. **Feature Request Template**
- **Title**: Feature Request: [Short description]
- **Description**: What new feature or improvement are you proposing?
- **Motivation**: Why is this feature important or useful?
- **Alternatives Considered**: List any alternatives that might solve the issue.
- **Additional Context**: Add any other context, screenshots, or links.

### 3. **General Inquiry or Discussion Template**
- **Title**: [Type of inquiry]: [Short description]
- **Description**: Provide details or ask a question about a feature, code snippet, or any other project-related issue.
- **Expected Outcome**: What do you hope to achieve or clarify?

### Additional Notes:
We can customize the templates further based on the team's preferences and needs. Once approved, these templates will be added to the `.github/ISSUE_TEMPLATE/` directory of the repository.

**Comment by YarosMallorca** [comment]
Thanks! Implemented in d6d250ecb9a91f18972a682c5a841026a4bea44a
