### ISSUE TITLE
Request for License File

### ISSUE THREAD

**Issue by Bashamega** [open-transport-mallorca/ViaMallorca#2]
We need to add a license to the repository to clarify the terms of use, contribution, and distribution for the project. Having a proper license will make it easier for contributors to understand their rights and responsibilities when contributing to the project.

### Suggested Licenses:
1. **MIT License**: A permissive license allowing reuse within proprietary software as long as all copies of the licensed software include the original license.
2. **GPLv3**: A copyleft license that requires anyone who distributes the code or derivative works to make the source available under the same license.
3. **Apache License 2.0**: A permissive license that also provides an express grant of patent rights from contributors to users.
4. **Other**: (Please specify if there’s a different preferred license.)

### Benefits of Having a License:
- Clearly defines usage and contribution guidelines.
- Protects contributors and users legally.
- Encourages contributions from a wider audience.
- Makes the project compatible with open-source initiatives.

### Action Steps:
- Decide on the appropriate license for this project.
- Add a `LICENSE` file to the root of the repository with the chosen license text.

**Comment by YarosMallorca** [comment]
Added in a7eaaa17d8786d44ddf5ef40ae024e19dc17310d
